export const authentication$API_GATEWAY = 'API_GATEWAY'
export const authentication$SERVER = 'EXPRESS'
export const authentication$ENUM = [authentication$API_GATEWAY, authentication$SERVER]
export const httpmethods$DELETE = 'DELETE'
export const httpmethods$GET = 'GET'
export const httpmethods$PATCH = 'PATCH'
export const httpmethods$POST = 'POST'
export const httpmethods$PUT = 'PUT'
export const keys$CLAIMS = 'organizations'
export const keys$USER_ID = 'user_id'
export const keys$ORGANIZATION_GROUP = 'organization_group'
export const keys$ORGANIZATION_ID = 'organization_id'
export const keys$ROLES = 'roles'
export const statuscodes$UNAUTHORIZED = 401
export const statuscodes$FORBIDDEN = 403
export const tokenverify$JWK = 'JWK'
export const tokenverify$PEM = 'PEM'
export const tokenverify$PLAIN_TEXT = 'PLAIN_TEXT'
export const tokenverify$ENUM = [tokenverify$JWK, tokenverify$PEM, tokenverify$PLAIN_TEXT]
